{"uid":"c6c8b0bc50664803","name":"test_delete_user_authorized_as_another_user","fullName":"tests.test_user_delete.TestUserDelete#test_delete_user_authorized_as_another_user","historyId":"f921dd3d5d139c34912ef23ea50982dc","time":{"start":1723957671531,"stop":1723957677093,"duration":5562},"description":"This test verifies that one user cannot delete another user","descriptionHtml":"<p>This test verifies that one user cannot delete another user</p>\n","status":"passed","statusMessage":"XPASS This test is expected to fail due to a known defect","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"This test verifies that one user cannot delete another user","status":"passed","statusMessage":"XPASS This test is expected to fail due to a known defect","steps":[{"name":"POST request to URL '/user/'","time":{"start":1723957671531,"stop":1723957673031,"duration":1500},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"POST request to URL '/user/'","time":{"start":1723957673031,"stop":1723957674133,"duration":1102},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"POST request to URL '/user/login'","time":{"start":1723957674134,"stop":1723957674712,"duration":578},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"DELETE request to URL '/user/102896'","time":{"start":1723957674712,"stop":1723957675903,"duration":1191},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"GET request to URL '/user/102896'","time":{"start":1723957675903,"stop":1723957677093,"duration":1190},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":5,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"epic","value":"User Deletion Tests"},{"name":"tag","value":"@pytest.mark.xfail(reason='This test is expected to fail due to a known defect')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_user_delete"},{"name":"subSuite","value":"TestUserDelete"},{"name":"host","value":"fv-az773-934"},{"name":"thread","value":"2271-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_user_delete"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":158,"passed":157,"unknown":0,"total":315},"items":[{"uid":"cc5fb35a528a6aac","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/316//#testresult/cc5fb35a528a6aac","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723871301959,"stop":1723871306381,"duration":4422}},{"uid":"1912bcd6e9b16aeb","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/315//#testresult/1912bcd6e9b16aeb","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723784898383,"stop":1723784903535,"duration":5152}},{"uid":"bc991eeee069e168","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/314//#testresult/bc991eeee069e168","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723698546508,"stop":1723698550705,"duration":4197}},{"uid":"1ca2b8044ce0854","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/313//#testresult/1ca2b8044ce0854","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723612120763,"stop":1723612125749,"duration":4986}},{"uid":"2bd8019e7116d6ac","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/312//#testresult/2bd8019e7116d6ac","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723525725953,"stop":1723525730840,"duration":4887}},{"uid":"9202d1ff923fedbe","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/311//#testresult/9202d1ff923fedbe","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723439326216,"stop":1723439330625,"duration":4409}},{"uid":"c9f09dcc087db411","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/310//#testresult/c9f09dcc087db411","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nrequests.exceptions.SSLError: HTTPSConnectionPool(host='playground.learnqa.ru', port=443): Max retries exceeded with url: /api/user/ (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006)')))","time":{"start":1723352846246,"stop":1723352846483,"duration":237}},{"uid":"85760dca2c72bd19","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/309//#testresult/85760dca2c72bd19","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723266475124,"stop":1723266480745,"duration":5621}},{"uid":"67bed9f9d46cca12","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/308//#testresult/67bed9f9d46cca12","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723180134116,"stop":1723180139131,"duration":5015}},{"uid":"a435fc12e135b233","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/307//#testresult/a435fc12e135b233","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723093743487,"stop":1723093749132,"duration":5645}},{"uid":"54c76fc69e33c32b","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/306//#testresult/54c76fc69e33c32b","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723007295897,"stop":1723007300284,"duration":4387}},{"uid":"206cb9dcf071b16f","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/305//#testresult/206cb9dcf071b16f","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1722920917527,"stop":1722920921999,"duration":4472}},{"uid":"cdf97ce67fc24d91","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/304//#testresult/cdf97ce67fc24d91","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1722834610739,"stop":1722834615181,"duration":4442}},{"uid":"eeafcec54a659ee","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/303//#testresult/eeafcec54a659ee","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1722748061453,"stop":1722748066951,"duration":5498}},{"uid":"51a93034fbf91e92","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/302//#testresult/51a93034fbf91e92","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1722661661751,"stop":1722661666205,"duration":4454}},{"uid":"199a793c42beb97b","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/301//#testresult/199a793c42beb97b","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1722575285126,"stop":1722575290425,"duration":5299}},{"uid":"c435a04929b93b6b","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/300//#testresult/c435a04929b93b6b","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1722488897500,"stop":1722488902253,"duration":4753}},{"uid":"787da3cd7f0f3af7","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/299//#testresult/787da3cd7f0f3af7","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1722402464750,"stop":1722402468901,"duration":4151}},{"uid":"56300cf95f250b5c","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/298//#testresult/56300cf95f250b5c","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1722316154913,"stop":1722316160204,"duration":5291}},{"uid":"d2c3bdd78380cdc3","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/297//#testresult/d2c3bdd78380cdc3","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1722229773427,"stop":1722229779001,"duration":5574}}]},"tags":["@pytest.mark.xfail(reason='This test is expected to fail due to a known defect')"]},"source":"c6c8b0bc50664803.json","parameterValues":[]}