{"uid":"108534a550529a9d","name":"test_delete_user_authorized_as_another_user","fullName":"tests.test_user_delete.TestUserDelete#test_delete_user_authorized_as_another_user","historyId":"f921dd3d5d139c34912ef23ea50982dc","time":{"start":1710479299779,"stop":1710479304944,"duration":5165},"description":"This test verifies that one user cannot delete another user","descriptionHtml":"<p>This test verifies that one user cannot delete another user</p>\n","status":"passed","statusMessage":"XPASS This test is expected to fail due to a known defect","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"This test verifies that one user cannot delete another user","status":"passed","statusMessage":"XPASS This test is expected to fail due to a known defect","steps":[{"name":"POST request to URL '/user/'","time":{"start":1710479299779,"stop":1710479300869,"duration":1090},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"POST request to URL '/user/'","time":{"start":1710479300869,"stop":1710479301950,"duration":1081},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"POST request to URL '/user/login'","time":{"start":1710479301951,"stop":1710479302531,"duration":580},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"DELETE request to URL '/user/94696'","time":{"start":1710479302531,"stop":1710479303714,"duration":1183},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"GET request to URL '/user/94696'","time":{"start":1710479303714,"stop":1710479304940,"duration":1226},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":5,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"epic","value":"User Deletion Tests"},{"name":"tag","value":"@pytest.mark.xfail(reason='This test is expected to fail due to a known defect')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_user_delete"},{"name":"subSuite","value":"TestUserDelete"},{"name":"host","value":"fv-az801-159"},{"name":"thread","value":"2352-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_user_delete"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":151,"passed":8,"unknown":0,"total":159},"items":[{"uid":"6cbfb2e0cc3b8a68","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/160//#testresult/6cbfb2e0cc3b8a68","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1710392834357,"stop":1710392838882,"duration":4525}},{"uid":"adb729035fed4f83","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/159//#testresult/adb729035fed4f83","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1710306464427,"stop":1710306469271,"duration":4844}},{"uid":"4bdfdb63cf0428e1","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/158//#testresult/4bdfdb63cf0428e1","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1710220136398,"stop":1710220141411,"duration":5013}},{"uid":"bc9da528b9636a45","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/157//#testresult/bc9da528b9636a45","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1710133645361,"stop":1710133649983,"duration":4622}},{"uid":"8da9cd970df57af8","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/156//#testresult/8da9cd970df57af8","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1710047174971,"stop":1710047180001,"duration":5030}},{"uid":"b2161edf1de21ec8","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/155//#testresult/b2161edf1de21ec8","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1709960883291,"stop":1709960888201,"duration":4910}},{"uid":"4a8f3cacd5cda1da","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/154//#testresult/4a8f3cacd5cda1da","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1709874472893,"stop":1709874477504,"duration":4611}},{"uid":"580b717d8d7cf28","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/153//#testresult/580b717d8d7cf28","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1709788001418,"stop":1709788005185,"duration":3767}},{"uid":"286da7f526e96654","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/152//#testresult/286da7f526e96654","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1709701615062,"stop":1709701619021,"duration":3959}},{"uid":"3b793e5fb9920855","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/151//#testresult/3b793e5fb9920855","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1709615240592,"stop":1709615244448,"duration":3856}},{"uid":"2080d8a043a94bbf","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/150//#testresult/2080d8a043a94bbf","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1709530884615,"stop":1709530888095,"duration":3480}},{"uid":"9246ba2951849e5d","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/149//#testresult/9246ba2951849e5d","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1709442428244,"stop":1709442432166,"duration":3922}},{"uid":"b75b37e511f98dd9","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/148//#testresult/b75b37e511f98dd9","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1709356053858,"stop":1709356057998,"duration":4140}},{"uid":"f788fc51e3364fec","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/147//#testresult/f788fc51e3364fec","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1709269671408,"stop":1709269675197,"duration":3789}},{"uid":"1047d28714dbad79","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/146//#testresult/1047d28714dbad79","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1709183309495,"stop":1709183313730,"duration":4235}},{"uid":"465e173f2130a36e","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/145//#testresult/465e173f2130a36e","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1709096894001,"stop":1709096898037,"duration":4036}},{"uid":"95438340a0f0212b","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/144//#testresult/95438340a0f0212b","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1709010486181,"stop":1709010489433,"duration":3252}},{"uid":"5e3d54345afe6a21","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/143//#testresult/5e3d54345afe6a21","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1708924068982,"stop":1708924073403,"duration":4421}},{"uid":"6e31e1d9fca6b49","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/142//#testresult/6e31e1d9fca6b49","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1708837547590,"stop":1708837551282,"duration":3692}},{"uid":"2d1a566a48c6a5cf","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/141//#testresult/2d1a566a48c6a5cf","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code","time":{"start":1708751234450,"stop":1708751239962,"duration":5512}}]},"tags":["@pytest.mark.xfail(reason='This test is expected to fail due to a known defect')"]},"source":"108534a550529a9d.json","parameterValues":[]}