{"name": "test_delete_user_authorized_as_another_user", "status": "skipped", "statusDetails": {"message": "XFAIL This test is expected to fail due to a known defect\n\nAssertionError: Unexpected status code 200\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_user_delete.TestUserDelete object at 0x000002B9FA40A610>\n\n    @pytest.mark.xfail(reason=\"This test is expected to fail due to a known defect\")\n    def test_delete_user_authorized_as_another_user(self):\n        # Создание двух пользователей\n        first_user_data = self.preapare_registration_data()\n        response_first_user = MyRequests.post(\"/user/\", data=first_user_data)\n        first_user_id = self.get_json_value(response_first_user, \"id\")\n        second_user_data = self.preapare_registration_data()\n        MyRequests.post(\"/user/\", data=second_user_data)\n    \n        # Авторизация под вторым пользователем\n        response1 = MyRequests.post(\"/user/login\",\n                                    data={'email': second_user_data['email'], 'password': second_user_data['password']})\n        auth_sid = self.get_cookie(response1, \"auth_sid\")\n        token = self.get_header(response1, \"x-csrf-token\")\n    \n        # Попытка удалить первого пользователя из-под учетной записи второго пользователя\n        response2 = MyRequests.delete(f\"/user/{first_user_id}\",\n                                      headers={\"x-csrf-token\": token},\n                                      cookies={\"auth_sid\": auth_sid})\n>       assert response2.status_code == 400, f\"Unexpected status code {response2.status_code}\"\nE       AssertionError: Unexpected status code 200\nE       assert 200 == 400\nE        +  where 200 = <Response [200]>.status_code\n\ntests\\test_user_delete.py:66: AssertionError"}, "steps": [{"name": "POST request to URL '/user/'", "status": "passed", "start": 1697058832051, "stop": 1697058832999}, {"name": "POST request to URL '/user/'", "status": "passed", "start": 1697058832999, "stop": 1697058833883}, {"name": "POST request to URL '/user/login'", "status": "passed", "start": 1697058833886, "stop": 1697058834642}, {"name": "DELETE request to URL '/user/82100'", "status": "passed", "start": 1697058834642, "stop": 1697058835698}], "start": 1697058832051, "stop": 1697058835698, "uuid": "21b2278c-41ac-4517-81a5-24f5f6200c7b", "historyId": "f921dd3d5d139c34912ef23ea50982dc", "testCaseId": "f921dd3d5d139c34912ef23ea50982dc", "fullName": "tests.test_user_delete.TestUserDelete#test_delete_user_authorized_as_another_user", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='This test is expected to fail due to a known defect')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_delete"}, {"name": "subSuite", "value": "TestUserDelete"}, {"name": "host", "value": "LAPTOP-SFQ2DO00"}, {"name": "thread", "value": "17712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_delete"}]}