{"uid":"3da22d9afe7906e6","name":"test_delete_user_authorized_as_another_user","fullName":"tests.test_user_delete.TestUserDelete#test_delete_user_authorized_as_another_user","historyId":"f921dd3d5d139c34912ef23ea50982dc","time":{"start":1724908130398,"stop":1724908136023,"duration":5625},"description":"This test verifies that one user cannot delete another user","descriptionHtml":"<p>This test verifies that one user cannot delete another user</p>\n","status":"passed","statusMessage":"XPASS This test is expected to fail due to a known defect","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"description":"This test verifies that one user cannot delete another user","status":"passed","statusMessage":"XPASS This test is expected to fail due to a known defect","steps":[{"name":"POST request to URL '/user/'","time":{"start":1724908130398,"stop":1724908131509,"duration":1111},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"POST request to URL '/user/'","time":{"start":1724908131509,"stop":1724908133006,"duration":1497},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"POST request to URL '/user/login'","time":{"start":1724908133007,"stop":1724908133596,"duration":589},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"DELETE request to URL '/user/103622'","time":{"start":1724908133596,"stop":1724908134805,"duration":1209},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"GET request to URL '/user/103622'","time":{"start":1724908134805,"stop":1724908136023,"duration":1218},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":5,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"epic","value":"User Deletion Tests"},{"name":"tag","value":"@pytest.mark.xfail(reason='This test is expected to fail due to a known defect')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_user_delete"},{"name":"subSuite","value":"TestUserDelete"},{"name":"host","value":"fv-az1771-326"},{"name":"thread","value":"2237-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_user_delete"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":0,"broken":0,"skipped":158,"passed":168,"unknown":0,"total":326},"items":[{"uid":"8ab2d2dfcdd06c39","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/327//#testresult/8ab2d2dfcdd06c39","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1724821709237,"stop":1724821714417,"duration":5180}},{"uid":"e20593cfbc36ee72","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/326//#testresult/e20593cfbc36ee72","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1724735308868,"stop":1724735313322,"duration":4454}},{"uid":"17629afcc48d4900","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/325//#testresult/17629afcc48d4900","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1724648923724,"stop":1724648928167,"duration":4443}},{"uid":"4095036ad9b5c06b","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/324//#testresult/4095036ad9b5c06b","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1724562528148,"stop":1724562532536,"duration":4388}},{"uid":"c04c74c9c8173656","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/323//#testresult/c04c74c9c8173656","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1724476065395,"stop":1724476070483,"duration":5088}},{"uid":"a5e2ec60f61a15c2","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/322//#testresult/a5e2ec60f61a15c2","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1724389722080,"stop":1724389726818,"duration":4738}},{"uid":"189bf69f9f8829d6","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/321//#testresult/189bf69f9f8829d6","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1724303297671,"stop":1724303302058,"duration":4387}},{"uid":"12bcf3d42220a914","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/320//#testresult/12bcf3d42220a914","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1724216914827,"stop":1724216919910,"duration":5083}},{"uid":"3e6ab33b1fecffdc","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/319//#testresult/3e6ab33b1fecffdc","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1724130492151,"stop":1724130496600,"duration":4449}},{"uid":"b28d3138ae784bcf","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/318//#testresult/b28d3138ae784bcf","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1724044116430,"stop":1724044121190,"duration":4760}},{"uid":"c6c8b0bc50664803","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/317//#testresult/c6c8b0bc50664803","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723957671531,"stop":1723957677093,"duration":5562}},{"uid":"cc5fb35a528a6aac","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/316//#testresult/cc5fb35a528a6aac","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723871301959,"stop":1723871306381,"duration":4422}},{"uid":"1912bcd6e9b16aeb","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/315//#testresult/1912bcd6e9b16aeb","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723784898383,"stop":1723784903535,"duration":5152}},{"uid":"bc991eeee069e168","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/314//#testresult/bc991eeee069e168","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723698546508,"stop":1723698550705,"duration":4197}},{"uid":"1ca2b8044ce0854","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/313//#testresult/1ca2b8044ce0854","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723612120763,"stop":1723612125749,"duration":4986}},{"uid":"2bd8019e7116d6ac","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/312//#testresult/2bd8019e7116d6ac","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723525725953,"stop":1723525730840,"duration":4887}},{"uid":"9202d1ff923fedbe","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/311//#testresult/9202d1ff923fedbe","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723439326216,"stop":1723439330625,"duration":4409}},{"uid":"c9f09dcc087db411","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/310//#testresult/c9f09dcc087db411","status":"skipped","statusDetails":"XFAIL This test is expected to fail due to a known defect\n\nrequests.exceptions.SSLError: HTTPSConnectionPool(host='playground.learnqa.ru', port=443): Max retries exceeded with url: /api/user/ (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1006)')))","time":{"start":1723352846246,"stop":1723352846483,"duration":237}},{"uid":"85760dca2c72bd19","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/309//#testresult/85760dca2c72bd19","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723266475124,"stop":1723266480745,"duration":5621}},{"uid":"67bed9f9d46cca12","reportUrl":"https://Badx86.github.io/LearnQA_Python_API/308//#testresult/67bed9f9d46cca12","status":"passed","statusDetails":"XPASS This test is expected to fail due to a known defect","time":{"start":1723180134116,"stop":1723180139131,"duration":5015}}]},"tags":["@pytest.mark.xfail(reason='This test is expected to fail due to a known defect')"]},"source":"3da22d9afe7906e6.json","parameterValues":[]}